### ISSUE TITLE
bildausschnitt (evtl. schon gefixt)

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/claudiodilucia#12]
claudio hatte an einer stelle noch eine anmerkung zum bildausschnitt. daß seine mädels irgendwie komisch angeschnitten wären. ich bekomme das bei mir nicht rekonstruiert. weiß du noch was genau da seine anmerkung war und ob du das evtl. bereits gefixt hast?

**Comment by kremin** [comment]
Gefixt. 

i.A. Daniel Kremin
Dipl. Des. | Creative Direction Interactive

___________________________________________

CADMAN
Real Estate Marketing

T	+49 211 86752-15
F	+49 211 86752-11
M	+49 175 184 57 89
@	kremin@cadman.de
w	www.cadman.de
___________________________________________

CADMAN GmbH – Real Estate Marketing
Kaiserswerther Straße 183 a • D-40474 Düsseldorf

___________________________________________

CADMAN GmbH – Real Estate Marketing
Freie-Vogel-Strasse 393 • D-44269 Dortmund

___________________________________________

CADMAN GmbH – Real Estate Marketing
Heckscherstraße 48a • D-20253 Hamburg

___________________________________________

Geschäftsführer: Marc Kömmerling • Dipl.-Kfm. Peter Jücker
Düsseldorf HRB 41966 • Steuer-Nr. 105/5807/2525
