### ISSUE TITLE
mobil sind die bilder in der galerie noch abgeschnitten

### ISSUE THREAD

**Issue by Matteng123** [youonlyliveonce/claudiodilucia#18]
![unnamed](https://user-images.githubusercontent.com/19430535/33856463-82c6ab20-dec8-11e7-8774-d5bdfa656980.png)

**Comment by kremin** [comment]
wir hatten auch nur gesagt, dass die Bilder in der Fullscreenansicht im ganzen zu sehen sind. wenn ich hier die Bilder wie org. anzeige ist dein layout völlig zerstört. wie soll das gehen?

**Comment by Matteng123** [comment]
hast recht, hier geht es nicht. funktional sollten wir das so lassen wie du vorgeschlagen hast. bei mir poppt unten nur immer die schnellnavi rein und überlagert den rest. das sollten wir dann rausnehmen. dann ist die erste "normale" ansicht quasi die schnellnavi.
